//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : See51
//  @ File Name : backParentListener.java
//  @ Date : 2013-8-14
//  @ Author : Eric Huang <htb@my51c.com>
//
//
package com.my51c.see51.listener;

/** 
* 返回父层监听接口 <br> 
***** &nbsp;&nbsp需要监听返回父层点击事件的对象实现该接口，<br>
*当点击返回按键时并且需要返回上一层时，调用此接口
*/ 
public interface BackParentListener
{
	public void backParent();
}


