//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : See51
//  @ File Name : MediaStreamer.java
//  @ Date : 2012-5-30
//  @ Author : Eric Guo <gjl@my51c.com>
//
//



package com.my51c.see51.media;

import com.my51c.see51.listener.OnAVQSetListener;
import com.my51c.see51.listener.OnAlarmEnableListener;
import com.my51c.see51.listener.OnIntercomListener;

import java.io.PipedOutputStream;
import java.io.Serializable;
import java.nio.ByteBuffer;
import java.util.Map;

/**
 * ��ý�������
 * @author guo
 *
 */
public abstract class MediaStreamer implements Serializable {
	
	protected MediaEventListener dataListener;
	protected String hostAddr;
	protected int port;
	protected Map<String, String> paramMap;
	public int m_bAlarmEnable;
	public int m_nDefinitionCurrent;
	
	
	final int DATA_BUFFER_SIZE = 10*680*480*3;
	
	/**
	 * ��ý������๹�캯��
	 * @param url ý���ַ
	 * @param param ��ʼ������
	 */
	public MediaStreamer(String url, Map<String, String>param)
	{
		String arrayStr[] = url.split(":");
		this.hostAddr = arrayStr[0];
		if(arrayStr.length > 1)
		{
			this.port = Integer.parseInt(arrayStr[1]);
		}
		this.paramMap = param;
	}

	/**
	 * ����ý��
	 * @return true: �ɹ�  false��ʧ��
	 */
	public abstract boolean open();
	/**
	 * �ر���ý��
	 */
	public abstract void close();
	
	/**
	 * ��ȡһ֡��Ƶ���� 
	 * @param timout ��ʱʱ�䣬��λ���룻0��ʾ���ȴ�, -1��ʾ�����ڵȴ�
	 * @return һ����Ƶ����
	 */
	public abstract VideoFrame getOneVideoFrame(int timout);
	/**
	 * ��ȡһ����Ƶ��
	 * @param timeout ��ʱʱ�䣬��λ���룻0��ʾ���ȴ�, -1��ʾ�����ڵȴ�
	 * @return ��Ƶ������
	 */
	public abstract byte[] getOneAudioPack(int timeout);
	/**
	 * ��ȡһ֡���ݣ�����ʱ
	 * @return
	 */
	public  VideoFrame getOneVideoFrame()
	{
		return getOneVideoFrame(-1);
	}
	
	public abstract void turnLeft();
	public abstract void turnRight();
	public abstract void rollUp();
	public abstract void rollDown();
	public abstract void zoomIn();
	public abstract void zoomOut();
	public abstract void restPtz();
	public abstract void scanV();
	public abstract void scanH();
	public abstract void scanStop();
	public abstract void zoomInPosition(int x, int y);
	public abstract void flipV();
	public abstract void flipH();
	public abstract void setAudio(boolean isEnable);
	public abstract void setVideo(boolean isEnable);
	public abstract void setInterCom(boolean isEnable);
	public abstract void setAlarmEnable();//add by marshal 20140503
	public abstract void getAlarmEnable();//add by hao 20141124
	public abstract void setDefinition();//add by marshal 20140503
	public abstract void focusIn();
	public abstract void focusOut();
	
	/**
	 * ��ȡһ����Ƶ���ݣ�����ʱ
	 * @return
	 */
	public  byte[] getOneAudioPack()
	{
		return getOneAudioPack(-1);
	}
	/**
	 * ���ý�����ݼ������������ݵ���ʱ֪ͨ������
	 * @return
	 */
	public void setMediaDataListener(MediaEventListener listener)
	{
		this.dataListener = listener;
	}
	
	/**
	 * ��ý���¼���
	 * @author guo
	 *
	 */
	public enum MediaEvent
	{
		/**
		 * ���ӳ�ʱ
		 */
		CONN_TIME_OUT("time out"),
		/**
		 * ���ӶϿ�
		 */
		CONN_DISCONNECT("disconnected");
		
		private String what;
		MediaEvent(String value)
		{
			this.what = value;
		}
		public String toString()
		{
			return this.what;
		}
	}
	
	
	/**
	 * ý���¼������ӿ�
	 * @author guo
	 *
	 */
	public interface MediaEventListener
	{
		/**
		 * ý���쳣�¼��ӿ�
		 * @param event
		 */
		public void OnMediaDataException(MediaEvent event);
	}
	
	/**
	 * ��Ƶ֡��
	 * @author guo
	 *
	 */
	public class VideoFrame
	{
		
		/**		typedef struct 
		//		{
		//			unsigned int	iKeyFrame; 
		//			unsigned int	iDataType;
		//			unsigned int	iDataSize;         
		//			unsigned int	gs_frameRate_samplingRate; 
		//			unsigned int	lTime;
		//			unsigned int	gs_video_cap;   
		//			unsigned int	gs_reserved; 
		//		}DATA_HEAD;
		*/
		
		private byte dataBuf[];
		private String szVersion;
		private boolean keyFrame;
		private int 	dataSize; // 1-��Ƶ 2-��Ƶ
		private int		frameRate; // FPS
		private	long 	timeStamp; // ��λms
		private int     videoCap; // 0~12λ����ʾ����ͷ��֧�ֵķֱ���
		private boolean alarmFrame;
		
		// �ӽ��յ������ݴ���һ����Ƶ֡
		public  VideoFrame(byte buf[])
		{
			if(buf != null)
			{
				ByteBuffer byteBuffer = ByteBuffer.wrap(buf);
				int nTmp = byteBuffer.getInt();
				keyFrame = ((nTmp&0xFF) != 0);
				alarmFrame = ((nTmp&0xFF00) != 0); 
				byteBuffer.getInt(); // dataType������
				dataSize = byteBuffer.getInt(); //dataSize
				frameRate = byteBuffer.getInt(); // ֡��
				nTmp = byteBuffer.getInt(); // ʱ���,���޷���ת�����з���
				timeStamp = nTmp& 0x0FFFFFFFFL;
				
				videoCap = byteBuffer.getInt(); // �豸����
				byteBuffer.getInt();  // ����reserved�ֶ�
				dataBuf = new byte[dataSize];
				byteBuffer.get(dataBuf);
			}
		}
		
		/**
		 * Э��汾
		 * @return
		 */
		public String getSzVersion() {
			return szVersion;
		}
		/**
		 * �Ƿ�ؼ�֡
		 * @return true:�ؼ�֡  false���ǹؼ�֡
		 */
		public boolean isKeyFrame() {
			return keyFrame;
		}
		/**
		 * ��ȡ����Ƶ���ݴ�С
		 * @return ����Ƶ���ݴ�С
		 */
		public int getDataSize() {
			return dataSize;
		}
		/**
		 * ��ȡ֡��
		 * @return ֡�� fps
		 */
		public int getFrameRate() {
			return frameRate;
		}
		/**
		 * ��ȡʱ���
		 * @return ��֡��ʱ�����UTCʱ�䣬ms
		 */
		public long getTimeStamp() {
			return timeStamp;
		}

		public int getVideoCap() {
			return videoCap;
		}
		/**
		 * �Ƿ��б���
		 * @return true: �б��� false���ޱ���
		 */
		public boolean isAlarmFrame() {
			return alarmFrame;
		}
		/**
		 * ��ȡ����Ƶ����
		 * @return ����Ƶ����
		 */
		public byte[] getFrameData()
		{
			return dataBuf;
		}
	}
	
	public void startSnapPic() {
		
	}
	
	public void sendAudioData(byte[] array) {
		// TODO Auto-generated method stub
		
	}

	public void stopIntercomm() {
		// TODO Auto-generated method stub
		
	}

	public void createAudioStream() {
		// TODO Auto-generated method stub
		
	}

	public PipedOutputStream getAudioStream() {
		// TODO Auto-generated method stub
		return null;
	}

	public void closeAudioStream() {
		// TODO Auto-generated method stub
		
	}

	public void setOnIntercomListener(OnIntercomListener mOnIntercomListener) {
		// TODO Auto-generated method stub
		
	}
	public void setOnAlarmEnableListener(OnAlarmEnableListener mOnAlarmEnalbeListener) {
		// TODO Auto-generated method stub
		
	}
	public void setOnAVQSetListener(OnAVQSetListener mOnAVQSetListener) {
		// TODO Auto-generated method stub
		
	}

}
