//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : See51
//  @ File Name : AccountInfo.java
//  @ Date : 2012-5-30
//  @ Author : Eric Guo <gjl@my51c.com>
//
//

package com.my51c.see51.data;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 * �˻���Ϣ��
 * 
 * @author guo
 * 
 */
public class AccountInfo
{
	private String username;
	private String password;
	private String email;
	private String nickname;
	private boolean logined; // �Ƿ��Ѿ���¼�ɹ�
	private boolean guest;
	private DeviceList myDevList;
	private DeviceList currentList;
	private Map<String, DeviceList> groMap;
	private ArrayList<AlarmInfo> alarmList;

	/**
	 * ���캯��
	 * 
	 * @param username
	 *            �û���
	 * @param password
	 *            ����
	 */
	public AccountInfo(String username, String password)
	{
		this.username = username;
		this.password = password;
		if (username.equals("guest"))
			this.guest = true;
		else
			this.guest = false;
		logined = false;
		setDevList(new DeviceList());
		setCurrentList(myDevList);
		groMap = Collections.synchronizedMap(new HashMap<String, DeviceList>());
	}

	/**
	 * ��ȡ�˻��ǳ�
	 * 
	 * @return �ǳ�
	 */
	public String getNickname()
	{
		return nickname;
	}

	/**
	 * �����˻��ǳ�
	 * 
	 * @param nickname
	 *            �ǳ�
	 */
	public void setNickname(String nickname)
	{
		this.nickname = nickname;
	}

	/**
	 * ��ȡ�û���
	 * 
	 * @return �û���
	 */
	public String getUsername()
	{
		return username;
	}

	/**
	 * �����û���
	 * 
	 * @param username
	 *            �û���
	 */
	public void setUsername(String username)
	{
		this.username = username;
	}

	/**
	 * ��ȡ����
	 * 
	 * @return ����
	 */
	public String getPassword()
	{
		return password;
	}

	/**
	 * ��������
	 * 
	 * @param password
	 *            ����
	 */
	public void setPassword(String password)
	{
		this.password = password;
	}

	/**
	 * ��ȡ�˻�email��ַ
	 * 
	 * @return email��ַ
	 */
	public String getEmail()
	{
		return email;
	}

	/**
	 * �����˻�email��ַ
	 * 
	 * @return email��ַ
	 */
	public void setEmail(String email)
	{
		this.email = email;
	}

	/**
	 * ��ȡ�˻���¼״̬
	 * 
	 * @return true���Ѿ���¼��false��δ��¼
	 */
	public boolean isLogined()
	{
		return logined;
	}

	/**
	 * �����˻���¼״̬
	 * 
	 * @param logined
	 *            true���Ѿ���¼��false��δ��¼
	 */
	public void setLogined(boolean logined)
	{
		this.logined = logined;
	}

	/**
	 * �Ƿ����˻��������˻�����װ��ʱʹ�ã�
	 * 
	 * @return �Ƿ����˻�
	 */
	public boolean isGuest()
	{
		return guest;
	}

	/**
	 * ��ȡ�˻��µ��豸�б�
	 * 
	 * @return �豸�б�
	 */
	public DeviceList getDevList()
	{
		return myDevList;
	}

	/**
	 * �����˻��µ��豸�б�
	 * 
	 * @param myDevList
	 *            �豸�б�
	 */
	public void setDevList(DeviceList myDevList)
	{
		this.myDevList = myDevList;
	}

	/**
	 * ��ȡ�˻��µĵ�ǰ��ʾ���豸�б�
	 * 
	 * @return ��ǰ��ʾ���豸�б�
	 */
	public DeviceList getCurrentList()
	{
		return currentList;
	}

	/**
	 * �����˻��µĵ�ǰ��ʾ���豸�б�
	 * 
	 * @param
	 *            �豸�б�
	 */
	public void setCurrentList(DeviceList currentList)
	{
		this.currentList = currentList;
	}

	/**
	 * ���˻�����������б�
	 * 
	 * @param
	 *            ���ID
	 */
	public void addList(Group parent_group, String grandParent_group)
	{
		if (!groMap.containsKey(parent_group))
		{
			DeviceList devList = new DeviceList();
			devList.setParent_group(parent_group);
			String groupId = parent_group.getGroupID();
			if (grandParent_group != null)
			{
				devList.setGrandParent_group(grandParent_group);
			}
			synchronized (this)
			{
				groMap.put(groupId, devList);
			}
		}

	}

	/**
	 * ��ȡ�˻��µ����е��б�
	 * 
	 * @param groupId
	 *            ���ID
	 * @return �豸�б�
	 */
	public DeviceList getDevList(String groupId)
	{
		DeviceList devList = this.groMap.get(groupId);
		if (devList != null)
			return devList;
		return null;
	}

	/**
	 * �򱨾���Ϣ�б�����ӱ�����Ϣ
	 * 
	 * @param alarmInfo
	 *            ������Ϣ
	 */
	public void addAlarmInfo(AlarmInfo alarmInfo)
	{
		if (alarmList == null)
			alarmList = new ArrayList<AlarmInfo>();
		alarmList.add(0, alarmInfo);
	}

	/**
	 * ��ȡ�˻��µı�����Ϣ�б�
	 * 
	 * @return ������Ϣ�б�
	 */
	public ArrayList<AlarmInfo> getAlarmList()
	{
		if (alarmList != null)
			return alarmList;
		return null;
	}
}
