//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : See51
//  @ File Name :GroupInfo.java
//  @ Date : 2013-08-08
//  @ Author : Eric Huang <htb@my51c.com>
//
//



package com.my51c.see51.data;

/**
 * 设备see51平台信息类
 * @author huang
 *
 */
public class Group {
	private String groupName;
	private String userName;
	private String version;
	private int devCount;
//	private String parentGroup;
//	private String grandparentGroup;
	private String groupID;
	
	public Group(String groupID)
	{
		this.groupID = groupID;
		this.groupName = null;
		this.userName = null;
		this.version = null;
	}
	/**
	 * 获取组名称
	 * @return 组名称 
	 */
	public String getGroupName() {
		return groupName;
	}
	/**
	 * 设置设备名称
	 * @param groupName 设备名称
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}
	/**
	 * 获取组所属账户名
	 * @return 账户名
	 */
	public String getUsername() {
		return userName;
	}
	/**
	 * 设置设备账户名
	 * @param username
	 */
	public void setUsername(String userName) {
		this.userName = userName;
	}
	/**
	 * 获取组ID
	 * @return 组ID
	 */
	public String getGroupID() {
		return groupID;
	}
	/**
	 * 获取组软件版本号 
	 * @return 软件版本号
	 */
	public String getVersion() {
		return version;
	}
	public void setVersion(String version) {
		this.version = version;
	}
	
	/**
	 * 获取本组设备数量 
	 * @return 设备数量
	 */
	public int getDevCount() {
		return devCount;
	}
	public void setDevCount(int devCount) {
		this.devCount = devCount;
	}
	
//	/**
//	 * 获取父组的ID 
//	 * @return 父组的ID
//	 */
//
//	public String getParentGroup()
//	{
//		return parentGroup;
//	}
//
//	public void setParentGroup(String parentGroup)
//	{
//		this.parentGroup = parentGroup;
//	}
//	/**
//	 * 获取爷组的ID  也就是上上层。 
//	 * @return 父组的ID
//	 */
//
//	public String getGrandparentGroup()
//	{
//		return grandparentGroup;
//	}
//
//	public void setGrandparentGroup(String grandparentGroup)
//	{
//		this.grandparentGroup = grandparentGroup;
//	}

	
}
